fix/cleanup dnuma-test.

diff --git a/bin/dnuma-test b/bin/dnuma-test
--- a/bin/dnuma-test
+++ b/bin/dnuma-test
@@ -7,16 +7,21 @@ usage() {
 	echo "       -- moves all memory to the node <node>"
 	echo "	     dnuma-test stripe <base-nid> <end-nid> <pfn-per-stripe>"
 	echo "       -- stripe memory between nodes <base-nid> and <end-nid>, inclusive"
-	echo "       -- For example, \`stripe 1 2 1\` results in 0-1:1,1-2:2,2-3:1,3-4:2"
+	echo "       -- For example, \`stripe 1 2 1\` results in 0-0:1,1-1:2,2-2:1,3-3:2"
 	exit 1
+}
+
+debug () {
+	[ -n "$DEBUG" ]
 }
 
 create_rme () {
 	# start end node
-	echo "creating rme $1 $2 $3"
-	printf "%d" "$1" > $M/start || echo "failed to write $1 to start"
-	printf "%d" "$2" > $M/end   || echo "failed to write $2 to end"
-	echo "$3" > $M/node  || echo "failed to write $3 to node"
+	local h_start=$(printf "0x%x" "$1") h_end=$(printf "0x%x" "$2")
+	debug && echo "creating rme $h_start $h_end $3"
+	echo "$h_start" > $M/start || echo "failed to write $h_start to start"
+	echo "$h_end"   > $M/end   || echo "failed to write $h_end to end"
+	echo "$3"       > $M/node  || echo "failed to write $3 to node"
 }
 
 [ $# -lt 1 ] && usage
@@ -34,9 +39,12 @@ a*)	[ $# -ne 1 ] && usage
 	;;
 	# stripe <base-nid> <end-nid> <pfn-per-stripe>
 s*)	[ $# -ne 3 ] && usage
-	pfn=0
-	nid=$1
+	base_nid=$1
+	end_nid=$2
 	pfn_per_stripe=$3
+
+	pfn=0
+	nid=$base_nid
 	while [ $pfn -lt $high_pfn ] ; do
 		: $((next_pfn = pfn + pfn_per_stripe - 1))
 		if [ $next_pfn -gt $high_pfn ]; then
@@ -44,8 +52,8 @@ s*)	[ $# -ne 3 ] && usage
 		fi
 		create_rme $pfn $next_pfn $nid
 		: $((nid = nid + 1))
-		if [ $nid -gt $2 ]; then
-			nid=$1;
+		if [ $nid -gt $end_nid ]; then
+			nid=$base_nid;
 		fi
 		: $((pfn = next_pfn + 1))
 	done
