rework of make-ktar

diff --git a/bin/make-ktar b/bin/make-ktar
--- a/bin/make-ktar
+++ b/bin/make-ktar
@@ -1,26 +1,121 @@
 #! /bin/sh
 
 D="$(dirname "$0")"
-export ARCH=powerpc
-export CROSS_COMPILE="ccache powerpc64-linux-"
-O=~/obj/linux-el7-ppc64
+
+usage () {
+	echo "usage: $(basename $0) \\"
+	echo "          [-a arch] [-c cross-compile-prefix] \\"
+	echo "		[-o output-dir] [-i install-dir] \\"
+	echo "		[-t [tarfile]] [-r rsync-not-yet-impl]"
+	echo ""
+	echo "environment var alternatives:"
+	echo "ARCH   -a"
+	echo "CROSS_COMPILE -c"
+	echo "O	-o"
+	echo "I -i"
+	exit 1
+}
+
+GEN_TARBALL=false
+TARBALL_NAME=
+while getopts a:c:i:o:t arg; do
+	case "$arg" in
+	a)	ARCH="$OPTARG"
+		;;
+	c)	CROSS_COMPILE="$OPTARG"
+		;;
+	i)	I="$OPTARG"
+		;;
+	o)	O="$OPTARG"
+		;;
+	t)	if [ -n "$OPTARG" ]; then
+			TARBALL_NAME="$OPTARG"
+		fi
+		GEN_TARBALL=true
+		;;
+	*)
+		usage
+	esac
+done
+
+case "$ARCH" in
+powerpc64)
+	ARCH=powerpc
+	if [ -z "$CROSS_COMPILE" ]; then
+		CROSS_COMPILE="powerpc64-linux-"
+	fi
+	;;
+esac
+
+if [ -z "$CROSS_COMPILE" ] && [ -n "$ARCH" ]; then
+	CROSS_COMPILE="$ARCH-linux-"
+fi
+
+CROSS_COMPILE="ccache $CROSS_COMPILE"
+
 MAKE_OPTS="-j8"
+
+echo "ARCH=$ARCH"
+echo "CROSS_COMPILE=$CROSS_COMPILE"
+echo "O=$O"
 
 die () {
 	echo "$*" >>/dev/stderr
 	exit 1
 }
 
-T=`mktemp -d`
-trap "rm -rf \"$T\"" EXIT
 
-make O="$O" $MAKE_OPTS || die "make failed"
-make O="$O" $MAKE_OPTS INSTALL_MOD_PATH="$T" modules_install || die "modules_install failed"
+if [ -n "$ARCH" ]; then
+	export ARCH
+fi
+if [ -n "$CROSS_COMPILE" ]; then
+	export CROSS_COMPILE
+fi
+make="make O=\"$O\" $MAKE_OPTS"
 
-make O="$O" $MAKE_OPTS INSTALL_PATH="$T" INSTALLKERNEL="$D/make-ktar.installkernel" install || die "install failed"
+r () {
+	"$@" || {
+		printf "Failed:\n\t"
+		for i in "$@"; do
+			e=$(printf "%s" "$i" | sed "s;';'\\'';" )
+			printf "'%s' " "$e"
+		done
+		printf "\n"
+		exit 1
+	}
+}
 
-# HACK HACK HACK
-VER=`cat "$T"/version`
+if [ -z "$I" ]; then
+	I=`mktemp -d`
+	trap "rm -rf \"$I\"" EXIT
+fi
 
-cd "$T" || die "can't get to $T"
-tar acf $O/linux-$ARCH-$VER.tar.xz . || die "failed to create tarball"
+r mkdir -p "$I"
+
+r $make
+r $make INSTALL_MOD_PATH="$I" modules_install
+
+VER=`$make kernelrelease | tail -n1`
+KERNEL=vmlinux
+MAP=System.map
+
+mkdir -p "$I/boot"
+r cp $O/$KERNEL  $I/boot/$KERNEL-$VER
+r cp $O/$MAP     $I/boot/$MAP-$VER
+r cp $O/.config  $I/boot/config-$VER
+r echo $VER > $I/version
+
+if $GEN_TARBALL; then
+	(
+		r cd "$I"
+
+		if [ -z "$TARBALL_NAME" ]; then
+			TARBALL_NAME=$O/linux-$ARCH-$VER.tar.xz
+		fi
+		r tar acf $O/linux-$ARCH-$VER.tar.xz .
+	)
+fi
+
+if $DO_RSYNC; then
+	# XXX: rsync it!
+fi
