music-to: use xargs or parallel, use bash builtin getopts

diff --git a/music-to b/music-to
--- a/music-to
+++ b/music-to
@@ -1,45 +1,50 @@
-#! /bin/sh
+#! /bin/bash
 set -eu -o pipefail
 
 usage() {
 	cat >&2 <<EOF
 usage: $0 -h
 usage: $0 [-fP] DEST_DIR SRC_DIR
-usage: $0 -X DEST_DIR SRC_DIR FILE_IN_SRC
+usage: $0 -X DEST_DIR SRC_DIR FILE_IN_SRC[...]
 
 flags:
 	-f	use find instead of direct iteration
-	-P	use parallel execution
-	-X	convert a single file (used internally)
+	-P	use parallel execution (via \`parallel\` or \`xargs\`)
+	-k	keep top level SRC_DIR inside DEST_DIR (useful if calling on a
+		single album dir)
+	-X	convert exactly these files (used internally)
 	-h	show help
 EOF
 	exit "$1"
 }
 
-opts=$(getopt -n "$0" -o "hfPX" -- "$@")
 use_find=false
 use_parallel=false
 convert_one=false
-eval set -- "$opts"
-while true; do
-	case "$1" in
-	-h) usage 0;;
-	-f) use_find=true;;
-	-P) use_parallel=true;;
-	-X) convert_one=true;;
-	--)
-		shift
-		break
-		;;
+keep_top_level_dir=false
+
+optstr="hkfPX"
+
+while getopts "$optstr" opt; do
+	case "$opt" in
+	h) usage 0;;
+	f) use_find=true;;
+	P) use_parallel=true;;
+	X) convert_one=true;;
+	k) keep_top_level_dir=true;;
+	\?) usage 1;;
+	*) >&2 echo "PROGRAMMING BUG: opt=$opt, OPTIND=$OPTIND"
+		exit 1;;
 	esac
-	shift
 done
+shift "$((OPTIND-1))"
+
 if $convert_one && ! [ $# -ge 3 ]; then
 	>&2 echo "-X requires 3 or more args"
 	usage 1
 fi
 if ! $convert_one && ! [ $# -eq 2 ]; then
-	>&2 echo "requires 2 args"
+	>&2 echo "requires 2 args (got $#)"
 	usage 1
 fi
 
@@ -50,6 +55,16 @@ shift 2
 if ! [ -d "$DEST_DIR" ]; then
 	>&2 echo "DEST_DIR='$DEST_DIR' does not exist"
 	exit 1
+fi
+
+if ! [ -d "$SRC_DIR" ]; then
+	>&2 echo "SRC_DIR='$SRC_DIR' does not exist"
+	exit 1
+fi
+
+if $keep_top_level_dir; then
+	DEST_DIR="$DEST_DIR/$(basename "$SRC_DIR")/"
+	mkdir -p "$DEST_DIR"
 fi
 
 # $1 = string
@@ -80,6 +95,7 @@ conv_one() {
 	*.flac|*.dsf|*.shn)
 		local non_ext="${f%.*}"
 		local R="$dest_dir/$(basename "$non_ext" | iconv -f UTF-8 -t ASCII//TRANSLIT).m4a"
+		# XXX: consider preserving 48k (downsample to 48k, avoid upsampling)
 		ffmpeg -hide_banner -y -i "$f" -c:a libfdk_aac -cutoff 18000 -b:a 192k -ar 44100 -ac 2 -vn "$R"
 		;;
 	*.log|*.[cC][uU][eE]|*.svf|*.md5|*.txt|*.[Jj][Pp][Gg]|*.m3u8|*.st5|*.png|*.ffp)
@@ -99,7 +115,7 @@ conv_one_x() {
 	local dest_dir="$DEST_DIR$(remove_prefix "$src_dir" "$SRC_DIR")"
 	mkdir -p "$dest_dir"
 
-	echo "FFFFF: $f"
+	>&2 echo "FFFFF: $f"
 	conv_one "$dest_dir" "$f"
 }
 
@@ -138,15 +154,43 @@ do_path_fe() {
 		-execdir "$x" "-X" "$DEST_DIR" "$SRC_DIR" \{\} \+
 }
 
+probe_parallel() {
+	HAVE_XARGS=false
+	HAVE_PARALLEL=false
+	if type parallel; then
+		HAVE_PARALLEL=true
+	elif type xargs; then
+		HAVE_XARGS=true
+		NUM_PROCS=$(getconf _NPROCESSORS_ONLN)
+	fi
+
+	>&2 echo "HAVE_XARGS=$HAVE_XARGS"
+	>&2 echo "HAVE_PARALLEL=$HAVE_PARALLEL"
+	: ${USE_PARALLEL:=$HAVE_PARALLEL}
+	: ${USE_XARGS:=$HAVE_XARGS}
+}
+
+do_parallel_x() {
+	if $USE_PARALLEL; then
+		parallel -0 -m "$@"
+	elif $USE_XARGS; then
+		xargs -0 -n 1 -P "${NUM_PROCS}" "$@"
+	else
+		>&2 echo "ERROR: no parallel mechanism found"
+		exit 1
+	fi
+}
+
 do_path_fp() {
-	local x="$(abspath "$0")"
+	probe_parallel
 	find "$1" \( -type f \( \
 		-name '*.flac' -or -name '*.dsf' -or \
 		-name '*.mp3' -or -name '*.m4a' -or \
 		-name '*.shn' \) \) \
 		-print0 | \
-		parallel -0 -m "$x" "-X" "$DEST_DIR" "$SRC_DIR"
+		do_parallel_x "$0" "-X" "$DEST_DIR" "$SRC_DIR"
 }
+
 
 if $convert_one; then
 	>&2 echo "CONV ONE"
